import pandas as pd
from src.core.data_loader import load_raw_data
from src.core.preprocessor import DataPreprocessor


class FeatureEngineer:
    def __init__(self):
        pass

    def create_features(self, df: pd.DataFrame) -> pd.DataFrame:
        feature_df = df.copy()

        # Generate lag inputs for precipitation
        feature_df['Precip_lag_1'] = feature_df['Precipitation_mm'].shift(1)
        feature_df['Precip_lag_2'] = feature_df['Precipitation_mm'].shift(2)
        feature_df['Precip_lag_3'] = feature_df['Precipitation_mm'].shift(3)

        # Generate lag inputs for target river level
        feature_df['River_Level_lag_1'] = feature_df['River_Level_m'].shift(1)

        # Generate rolling windows representing cumulative basin saturation
        feature_df['Precip_roll_mean_3'] = feature_df['Precipitation_mm'].rolling(window=3).mean()
        feature_df['Precip_roll_mean_7'] = feature_df['Precipitation_mm'].rolling(window=7).mean()

        # Remove edge NaN rows generated by shifts and rolling windows
        feature_df = feature_df.dropna().reset_index(drop=True)

        return feature_df


if __name__ == "__main__":
    print("Running Feature Engineer Test")
    try:
        raw_data = load_raw_data()
        preprocessor = DataPreprocessor()
        cleaned_data = preprocessor.clean_data(raw_data)

        engineer = FeatureEngineer()
        features_data = engineer.create_features(cleaned_data)

        print("Feature engineering completed successfully.")
        print(f"Dataset shape with features: {features_data.shape}")
        print("\nSample preview of engineered features:")

        preview_cols = [
            'Date', 'Precipitation_mm', 'Precip_lag_1',
            'Precip_roll_mean_3', 'River_Level_lag_1', 'River_Level_m'
        ]
        print(features_data[preview_cols].head())
    except Exception as e:
        print(f"Error during feature engineering: {e}")